version: '3.8'

services:
  api:
    image: elasticsearch
    container_name: api-elastic
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=akmal02032009
      - POSTGRES_DB=es
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akmal02032009
      POSTGRES_DB: es
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=your-elastic-password
      - xpack.security.enabled=true
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana-container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=_lfa9hanqZG8Wa98Yhi-
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - backend

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.1
    container_name: logstash-container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - '5044:5044'
    depends_on:
      - elasticsearch
    networks:
      - backend

volumes:
  postgres_data:
  es_data:

networks:
  backend:
    driver: bridge
