version: '1.0'
services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  
    environment:
      - POSTGRES_DB=es
      - POSTGRES_USER=localhost
      - POSTGRES_PASSWORD=akmal02032009
    networks:
      - my_network  

  elasticsearch:
    restart: always
    image: elasticsearch:7.8.1
    container_name: elasticsearch
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: 6nku5dQDNVT5?L@
    ports:
      - '9200:9200'  
      - '9300:9300'  
    networks:
      - my_network  

networks:
  my_network:
    driver: bridge  

volumes:
  elastic-data:
    driver: local  
